### ISSUE TITLE
Automatic reconnect not updating metrics

### ISSUE THREAD

**Issue by liamcottle** [rouyng/tncexporter#9] opened 2023-08-01 05:13 UTC
Hey! Thanks for this project, it's great to see some metrics, and I got it up and running pretty quickly. I also shared my systemd config in #6.

I've come across an issue where the automatic reconnect to the TNC after the connection has been lost is successful, but the metrics are never updated again. The only way for the metrics to be updated is if I kill the tncexporter process and restart it.

I'm connecting tncexporter to direwolf, and occasionally start/stop the direwolf process. From the logs below, you can see that metrics don't update after the connection to the TNC is re-established, but after restarting tncexporter, it is working again (since it doesn't use the reconnect logic).

I was just going to [edit the python script](https://github.com/rouyng/tncexporter/blob/master/tncexporter/listener.py#L127) to have it exit when the connection is lost, as I'm running this as a systemd service and it would just auto restart anyway, but wanted to make this known if you weren't aware.

```
pi@raspberrypi:~ $ journalctl -u tncexporter -f
-- Journal begins at Sat 2000-01-01 13:00:19 NZDT. --
Aug 01 17:00:35 raspberrypi env[502]: INFO: 01-Aug-23 17:00:35 - Attempting to connect to TNC at localhost:8000
Aug 01 17:00:35 raspberrypi env[502]: ERROR: 01-Aug-23 17:00:35 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:00:45 raspberrypi env[502]: INFO: 01-Aug-23 17:00:45 - Attempting to connect to TNC at localhost:8000
Aug 01 17:00:45 raspberrypi env[502]: ERROR: 01-Aug-23 17:00:45 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:00:55 raspberrypi env[502]: INFO: 01-Aug-23 17:00:55 - Attempting to connect to TNC at localhost:8000
Aug 01 17:00:55 raspberrypi env[502]: ERROR: 01-Aug-23 17:00:55 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:01:05 raspberrypi env[502]: INFO: 01-Aug-23 17:01:05 - Attempting to connect to TNC at localhost:8000
Aug 01 17:01:05 raspberrypi env[502]: ERROR: 01-Aug-23 17:01:05 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:01:15 raspberrypi env[502]: INFO: 01-Aug-23 17:01:15 - Attempting to connect to TNC at localhost:8000
Aug 01 17:01:15 raspberrypi env[502]: INFO: 01-Aug-23 17:01:15 - Connection established to TNC at localhost:8000
```

```
pi@raspberrypi:~ $ service tncexporter restart
```

```
pi@raspberrypi:~ $ journalctl -u tncexporter -f
-- Journal begins at Sat 2000-01-01 13:00:19 NZDT. --
Aug 01 17:00:55 raspberrypi env[502]: ERROR: 01-Aug-23 17:00:55 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:01:05 raspberrypi env[502]: INFO: 01-Aug-23 17:01:05 - Attempting to connect to TNC at localhost:8000
Aug 01 17:01:05 raspberrypi env[502]: ERROR: 01-Aug-23 17:01:05 - Could not connect to TNC at localhost:8000, connection refused. Retrying in 10 seconds
Aug 01 17:01:15 raspberrypi env[502]: INFO: 01-Aug-23 17:01:15 - Attempting to connect to TNC at localhost:8000
Aug 01 17:01:15 raspberrypi env[502]: INFO: 01-Aug-23 17:01:15 - Connection established to TNC at localhost:8000
Aug 01 17:03:44 raspberrypi systemd[1]: Stopping TNC Exporter...
Aug 01 17:03:44 raspberrypi systemd[1]: tncexporter.service: Succeeded.
Aug 01 17:03:44 raspberrypi systemd[1]: Stopped TNC Exporter.
Aug 01 17:03:44 raspberrypi systemd[1]: tncexporter.service: Consumed 5min 44.813s CPU time.
Aug 01 17:03:44 raspberrypi systemd[1]: Started TNC Exporter.
Aug 01 17:03:45 raspberrypi env[2642]: INFO: 01-Aug-23 17:03:45 - Attempting to connect to TNC at localhost:8000
Aug 01 17:03:49 raspberrypi env[2642]: INFO: 01-Aug-23 17:03:45 - Connection established to TNC at localhost:8000
Aug 01 17:03:49 raspberrypi env[2642]: INFO: 01-Aug-23 17:03:46 - Serving TNC prometheus metrics on: http://0.0.0.0:9110/metrics
Aug 01 17:03:49 raspberrypi env[2642]: INFO: 01-Aug-23 17:03:46 - Updated metrics for 0 packets
Aug 01 17:03:49 raspberrypi env[2642]: INFO: 01-Aug-23 17:03:48 - 10.1.0.103 [01/Aug/2023:05:03:48 +0000] "GET /metrics HTTP/1.1" 200 2543 "-" "Prometheus/2.44.0"
Aug 01 17:04:03 raspberrypi env[2642]: INFO: 01-Aug-23 17:04:03 - 10.1.0.103 [01/Aug/2023:05:04:03 +0000] "GET /metrics HTTP/1.1" 200 2543 "-" "Prometheus/2.44.0"
Aug 01 17:04:16 raspberrypi env[2642]: INFO: 01-Aug-23 17:04:16 - Updated metrics for 0 packets
Aug 01 17:04:18 raspberrypi env[2642]: INFO: 01-Aug-23 17:04:18 - 10.1.0.103 [01/Aug/2023:05:04:18 +0000] "GET /metrics HTTP/1.1" 200 2543 "-" "Prometheus/2.44.0"
```

**Comment by mateuszdrab** [comment] 2023-09-26 18:40
I had the same issue, I just added `sys.exit()` in the `except ConnectionResetError:` block as I'm not too familiar with asyncio and I think the issue is multi-threading related as I noticed the loops get blocked.

**Comment by rouyng** [comment] 2023-12-28 17:36
this should now be fixed in the commit referenced above. the socket defaults to blocking behavior when recreated after the connection to the TNC is reset. this was blocking the async task that updates metrics. fixed by setting the socket to nonblocking after it is recreated and reconnected. now, metrics should update after reconnection, as intended. please note that any packet metrics that are in queue waiting to be exported when the TNC is disconnected will not be exported to the prometheus endpoint until the TNC is reconnected. This is because the creation/connection of the socket runs synchronously. I will plan to fix this in the future so any queued packets are immediately exported when the connection drops.

**Closed by rouyng** 2023-12-28 17:36 UTC
