### ISSUE TITLE
Grafana 10.0 no longer reports list correctly

### ISSUE THREAD

**Issue by nx2i** [rouyng/tncexporter#8] opened 2023-06-25 14:21 UTC
![Screenshot from 2023-06-25 10-06-59](https://github.com/rouyng/tncexporter/assets/3056084/8edb542a-338e-40de-b228-85985ef465a1)
This has only recently changed.

**Comment by nx2i** [comment] 2023-07-12 11:35
Update.
The issue appears to be Grafana related. Downgrading the Grafana version from 10.0 to 9.5.5 eliminates the problem.

**Comment by rouyng** [comment] 2023-07-12 18:29
Thanks for following up with a possible root cause. I will leave this bug open and take a look when I have time to set up a proper testing environment with Grafana 10.0

**Comment by rouyng** [comment] 2023-07-16 18:11
Should be fixed in 286333629483dc1fe30af5b340b4bf02dccec6bf

**Closed by rouyng** 2023-07-16 18:11 UTC
Labels: bug
